issues:
  max-same-issues: 0
  exclude-use-default: false
  exclude-rules:
    - path: '_test\.go'
      linters:
        - bodyclose
        - gocognit
        - gocyclo
        - gosec
        - lll
        - prealloc

    # Overly picky
    - linters: [revive]
      text: 'package-comments'
    - linters: [revive]
      text: 'if-return'

    # Duplicates of errcheck
    - linters: [gosec]
      text: 'G104: Errors unhandled'
    - linters: [gosec]
      text: 'G307: Deferring unsafe method'

    # Contexts are best assigned defensively
    - linters: [ineffassign]
      text: 'ineffectual assignment to `ctx`'
    - linters: [staticcheck]
      text: 'SA4006: this value of `ctx` is never used'

    # Irrelevant for test examples
    - linters: [gocritic]
      path: example_test\.go
      text: 'exitAfterDefer'

run:
  timeout: 5m

linters:
  enable:
    - bodyclose
    - copyloopvar
    - errcheck
    - errchkjson
    - gocognit
    - gocritic
    - gocyclo
    - godot
    - gofumpt
    - goimports
    - gosec
    - intrange
    - lll
    - misspell
    - nakedret
    - nolintlint
    - perfsprint
    - prealloc
    - revive
    - sloglint
    - testifylint
    - unconvert
    - unparam

linters-settings:
  errcheck:
    exclude-functions:
      # Errors we wouldn't act on after checking
      - (*database/sql.DB).Close
      - (*database/sql.Rows).Close
      - (io.Closer).Close
      - (*os.File).Close
      - (net/http.ResponseWriter).Write

      # Handled by errchkjson
      - encoding/json.Marshal
      - encoding/json.MarshalIndent
      - (*encoding/json.Encoder).Encode

  gocognit:
    min-complexity: 10

  gocyclo:
    min-complexity: 10

  goimports:
    local-prefixes: github.com/morningconsult/grace

  govet:
    enable:
      - shadow

  nakedret:
    max-func-lines: 0

  revive:
    confidence: 0

  sloglint:
    args-on-sep-lines: true

  testifylint:
    enable-all: true
    disable:
      # Disallows valid use
      - require-error
