issues:
  max-same-issues: 0
  exclude-use-default: false
  exclude-rules:
    - path: '_test\.go'
      linters:
        - bodyclose
        - gocognit
        - goconst
        - gocyclo
        - gosec
        - lll
        - prealloc

    # Overly picky
    - linters: [revive]
      text: 'package-comments'
    - linters: [revive]
      text: 'if-return'

    # Duplicates of errcheck
    - linters: [gosec]
      text: 'G104: Errors unhandled'
    - linters: [gosec]
      text: 'G307: Deferring unsafe method'
    # Not a good rule since it ignores defaults
    - linters: [gosec]
      text: 'G112: Potential Slowloris Attack because ReadHeaderTimeout is not configured in the http.Server'

    # Contexts are best assigned defensively
    - linters: [ineffassign]
      text: 'ineffectual assignment to `ctx`'
    - linters: [staticcheck]
      text: 'SA4006: this value of `ctx` is never used'

    # Irrelevant for test examples
    - linters: [gocritic]
      path: example_test\.go
      text: 'exitAfterDefer'

run:
  timeout: 5m

linters:
  enable:
    - bodyclose
    - errcheck
    - errchkjson
    - exportloopref
    - goconst
    - gocognit
    - gocritic
    - gocyclo
    - godot
    - gofumpt
    - goimports
    - gosec
    - lll
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - revive
    - unconvert
    - unparam

linters-settings:
  errcheck:
    exclude-functions:
      # Errors we wouldn't act on after checking
      - (*database/sql.DB).Close
      - (*database/sql.Rows).Close
      - (io.Closer).Close
      - (*os.File).Close
      - (net/http.ResponseWriter).Write

      # Handled by errchkjson
      - encoding/json.Marshal
      - encoding/json.MarshalIndent
      - (*encoding/json.Encoder).Encode

  gocognit:
    min-complexity: 10

  goconst:
    min-len: 0
    min-occurrences: 3

  gocritic:
    disabled-checks:
      - appendAssign

  gocyclo:
    min-complexity: 10

  goimports:
    local-prefixes: github.com/morningconsult/grace

  golint:
    min-confidence: 0

  govet:
    check-shadowing: true

  nakedret:
    max-func-lines: 0

  revive:
    confidence: 0
